FROM memcached:latest

# NO NEED because these commands are executed by docker-compose.yml

#EXPOSE 11211

# Start Memcached in the background
# -u option to specify the user to run Memcached as -> david-memcache
# -vv option to enable verbose logging
# -m argument is used to specify the maximum memory size -> 128MB
# -p argument is used to specify the port number -> 11211
# CMD ["memcached", "-u", "david-memcache", "-vv", "-m", "128", "-p", "11211"]